---

- name: check if epel-release installed for CentOS
  yum:
    name:
      - epel-release
    state: present
  when:
    - ansible_distribution == 'CentOS'

- name: check if snapd installed for CentOS
  yum:
    name:
      - snapd
    state: present
  when:
    - ansible_distribution == 'CentOS'

- name: check if snapd installed for Ubuntu
  apt:
    name:
      - snapd
    state: present
  when:
    - ansible_distribution == 'Ubuntu'

- name: ensure snapd unit enabled
  systemd:
    name: snapd
    state: started
    enabled: yes
    masked: no

- name: check a symlink to snapd for CentOS
  file:
    src: /var/lib/snapd/snap
    dest: /snap
    state: link
  when:
    - ansible_distribution == 'CentOS'

- name: check if certbot installed
  snap:
    name:
      - certbot
    classic: yes
    state: present
  notify: get-first-cert

- name: check a symlink to certbot
  file:
    src: /snap/bin/certbot
    dest: /usr/bin/certbot
    state: link

- name: certbot-renew cronjob
  cron:
    name: "certbot-renew"
    job: "/usr/bin/certbot renew > /dev/null 2>&1"
    minute: '25'
    hour: '2'
    user: root
    state: present

- name: check certbot-ansible domain flag
  template:
    src: templates/certbot-ansible.flg.j2
    dest: /etc/certbot-ansible.flg
  notify: get-first-cert

- name: Flush handlers
  meta: flush_handlers
